name: ALPS

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  alps:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'
      - run: npm install -g @alps-asd/app-state-diagram
      - name: Generate ALPS diagram
        run: |
          if [ -f "docs/alps.json" ]; then
            asd docs/alps.json
          elif [ -f "docs/alps.xml" ]; then
            asd docs/alps.xml
          else
            echo "::error::No ALPS profile found (docs/alps.json or docs/alps.xml)"
            exit 1
          fi
      - uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: docs
      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
